apiVersion: apps/v1
kind: Deployment
metadata:
  name: blueskygreenbuilds-app
  namespace: blueskygreenbuild
  labels:
    app: blueskygreenbuilds-app
    version: "${FINAL_VERSION}"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: blueskygreenbuilds-app
      version: "${FINAL_VERSION}"
  template:
    metadata:
      labels:
        app: blueskygreenbuilds-app
        version: "${FINAL_VERSION}"
    spec:
      containers:
      - name: blueskygreenbuilds-app
        image: "${FINAL_IMAGE}" #quoted since it contains colon
        ports:
        - containerPort: 8080