apiVersion: apps/v1
kind: Deployment
metadata:
  name: blueskygreenbuilds-${FINAL_VERSION}
  namespace: blueskygreenbuild
  labels:
    app: blueskygreenbuilds
    version: "${FINAL_VERSION}" #must be string to successfully convert to json read by kubectl.
spec:
  replicas: 2
  selector:
    matchLabels:
      app: blueskygreenbuilds
      version: "${FINAL_VERSION}"
  template:
    metadata:
      labels:
        app: blueskygreenbuilds
        version: "${FINAL_VERSION}"
    spec:
      containers:
      - name: blueskygreenbuilds
        imagePullPolicy: Always
        image: "${FINAL_IMAGE}" #quoted since it contains colon
        ports:
        - containerPort: 8080
        livenessProbe:
          httpGet:
            path: /build-info
            port: http
            scheme: HTTP
          failureThreshold: 1
        resources:
          limits:
            memory: 512Mi
          requests:
            memory: 128Mi
        