version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk-browsers
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          key: circleci-challenge-{{ checksum "pom.xml" }}

      - run: mvn dependency:go-offline

      - save_cache:
          paths:
           - ~/.m2
          key: circleci-challenge-{{ checksum "pom.xml" }}


      - run:
          name: Install phantomjs
          command:
            curl -O https://github.com/ariya/phantomjs/releases/download/2.1.3/phantomjs


      - run:
          name: Build and test
          command:
            mvn package -Dphantomjs.binary.path="$PWD/phantomjs"

      - store_test_results:
          path: target/surefire-reports

      - store_artifacts:
          path: target/circleci-challenge-*.jar



workflows:
  version: 2
  build-deploy:
    jobs:
      - build