version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk-browsers
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          key: circleci-challenge-{{ checksum "pom.xml" }}

      - run: mvn dependency:go-offline

      - save_cache:
          paths:
           - ~/.m2
          key: circleci-challenge-{{ checksum "pom.xml" }}

      - run:
          name: Install phantomjs
          command:
            sudo apt-get install -y phantomjs

      - run:
          name: Build and test
          command: |
            mvn package -B
            cp target/circleci-challenge-*.jar /tmp/standalone-app.jar
            cp Procfile /tmp/Procfile

      - store_test_results:
          path: target/surefire-reports

      - store_artifacts:
          path: target/circleci-challenge-*.jar

      - persist_to_workspace:
                root: /tmp
                paths:
                  - standalone-app.jar

  deploy-stage:
    docker:
      - image: circleci/openjdk:8-jdk-browsers
    working_directory: ~/deploy
    steps:
      # why rebuild something we already tested, rebuilding invalidates any previous confidence?!
      - attach_workspace:
          at: /tmp
      - run:
          name: Run setup script
          command: bash .circleci/setup-heroku.sh
      - add_ssh_keys:
          fingerprints:
            - "61:5e:f5:cc:d6:58:84:c6:d2:af:68:0a:5d:e5:e4:f2"
      - run:
          name: Keroku Deploy
          command: |
            cp /tmp/standalone-app.jar .
            cp /tmp/Procfile .
            ls -la
            git push --force git@heroku.com:$HEROKU_APP_NAME.git HEAD:refs/heads/master


workflows:
  version: 2
  build-deploy:
    jobs:
      - build
      - deploy-stage:
          requires:
            - build